### ISSUE TITLE
DateTimePicker shows up twice when show mode set by onLongPress touchable opacity

### ISSUE THREAD

**Issue by jadeirving9** [react-native-community/react-native-datetimepicker#123]
# Bug

I am using several DateTimePickers which show on a button press, it works fine when completing a normal press, but if I set the button's onLongPress function to be the same as the onPress, the DateTimePicker opened by a different button will show as well as the new one. 

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz
    Memory: 441.11 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      Android NDK: 21.0.6113669
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6200805
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^4.0.0 => 4.0.1 
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: ^2.2.1

## Steps To Reproduce

I have two DateTimePickers, one to set the date and one to set the time, both open on a button press (they have their own respective buttons). Tried to add onLongPress functionality to both buttons (same function called as onPress), but if I long press on the date picker button, set the date and then long press on the time picker button, the date picker and the time picker opens - instead of just the time picker. 

Describe what you expected to happen:

onLongPress functionality to be the same as onPress - DateTimePicker to open on button press

**Comment by ppv94** [comment]
Can you provide me a sample you had implemented

**Comment by jadeirving9** [comment]
Of course, sorry.

`state={
   showDateTimePicker: true,
   dateTimePicker: null,
  }

render() {
   <View>
   <ToucableOpacity
      onPress={() => {
         // if the user has enabled long presses - ignore onPress function
         if (this.props.enabledLongPress === false) {
            this.handleButtonPress();
         }
      }}
      onLongPress={() => {
         this.handleButtonPress();
       }}>
      ...
   </TouchableOpacity>
   {this.state.showDateTimePicker && this.state.dateTimePicker}
   </View>
}

handleButtonPress() {
   this.setState({showDateTimePicker: true});
   this.setDateTimePicker('option1');
}

setDateTimePicker(value) {
   if (value === 'option1') {
      this.setState({
        dateTimePicker: (
          <DateTimePicker
            value={this.state.selectedDate}
            mode={'date'}
            display="default"
            minimumDate={today}
            maximumDate={yearFromToday}
            confirmBtnText="OK"
            cancelBtnText="Cancel"
            onChange={(event, date) => {
              if (event.type === 'set') {
                // hide the picker
                this.setState({showDateTimePicker: false});
                // do something with date
                ...
              }
            }}
          />
        ),
      });
}
`

**Comment by jadeirving9** [comment]
I've solved it by setting also dateTimePicker to null when I hide the picker
