### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by mateusz1913** [react-native-community/react-native-datetimepicker#17]
# Feature Request

Typescript definitions

## Why it is needed

It is needed for people who want to use this package in typescript projects

## Possible implementation

I could try made typings based on existing flow typings from src/types.js file.

### Code sample

Example in flow:
`export type IOSNativeProps = $ReadOnly<{|
  ...BaseProps,
  date?: ?Date,
  locale?: ?string,
  minuteInterval?: ?(1 | 2 | 3 | 4 | 5 | 6 | 10 | 12 | 15 | 20 | 30),
  mode?: IOSMode,
  timeZoneOffsetInMinutes?: ?number,
|}>;`
in Typescript would look sth like this:
`export type IOSNativeProps = Readonly<BaseProps & {
  date?: Date,
  locale?: string,
  minuteInterval?: (1 | 2 | 3 | 4 | 5 | 6 | 10 | 12 | 15 | 20 | 30),
  mode?: IOSMode,
  timeZoneOffsetInMinutes?: number,
}>;`

**Comment by SaeedZhiany** [comment]
It seems there is a file [here](https://github.com/react-native-community/react-native-datetimepicker/blob/master/src/types.js)

but I'm wondering why its extension is `.js` instead of `.ts` and not linked in `package.json` to automatically detected by typescript engine.

**Comment by mateusz1913** [comment]
Yes, there is a file with types, but it is for flow types system and there is no types definitions for typescript (changing only file extension won't work)

**Comment by SaeedZhiany** [comment]
Oh, you're right, I didn't know that.

> Could I submit PR with index.d.ts file?

we all will thank you if you can and take time to do that :)

**Comment by Swaagie** [comment]
Correct this was ported from the React-Native library with the flow definitions. I don't mind bringing in type definitions to unblock typescript devs. Imho I think we should move away from flow. I'm going to check what other community modules are doing wrt to that. Consider the PR merged and published with `minor` semver bump.
