### ISSUE TITLE
Debug app failed to build

### ISSUE THREAD

**Issue by siradityaverma** [react-native-community/react-native-datetimepicker#18]
# Question
Hi, after carefully following the steps, I get this error while building the app: 
```
com.android.build.api.transform.TransformException: Error while generating the main dex list:
  Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.reactcommunity.rndatetimepicker.BuildConfig
```

**Comment by phiphamuet** [comment]
You just install lib to node_modules. Do not manual add project to settings.gradle and build.gradle and build will success.

**Comment by vonovak** [comment]
If you're on RN 0.60 and newer, please remove any mentions of this module from the grade files and the error will go away. Autolinking will handle module installation. Thanks.
