### ISSUE TITLE
Is it possible to make a date picker only with month and year?

### ISSUE THREAD

**Issue by aidshon** [react-native-community/react-native-datetimepicker#23]
![photo_2019-09-04_17-03-55](https://user-images.githubusercontent.com/39763991/64309506-7975a600-cfbe-11e9-8921-2f1031403d70.jpg)

**Comment by Martian2Lee** [comment]
Yes, even only with the year!

**Comment by sameersitre** [comment]
How?

**Comment by AndyCrisan** [comment]
If someone can throw an example, in a comment, it would be of great help :D

**Comment by hai2san** [comment]
> Yes, even only with the year!

I couldn't see any config for this. Can you share me the details.

**Comment by anthonnyc2** [comment]
Anyone has found a solution for this? @Martian2Lee could you give us an example.

**Comment by wisquimas** [comment]
@aidshon use https://github.com/vinodkumar8/react-native-month-selector

**Comment by Thembelani** [comment]
I think Martin is asking if it's possible to only see the years. He doesn't have a solution.

**Comment by dquessenberry** [comment]
I would love to have this feature. For the project I am working on only month and year are required and the day is actually a bit of a UX hurdle for our users. I can't seem to find any quality date picker for month and year only and have an easy way to quickly jump years ahead.

**Comment by pranjaljately** [comment]
> I would love to have this feature. For the project I am working on only month and year are required and the day is actually a bit of a UX hurdle for our users. I can't seem to find any quality date picker for month and year only and have an easy way to quickly jump years ahead.

Did you happen to find any?

**Comment by vonovak** [comment]
According to [SO](https://stackoverflow.com/questions/3348247/uidatepicker-select-month-and-year) this is not possible with `UIDatePicker` so I'm not planning to implement this. Workaround can be bridging some 3rd part picker to React Native.

**Comment by RayyanNafees** [comment]
try this package
https://www.npmjs.com/package/react-native-month-year-picker

**Comment by raiabdullahbashir** [comment]
> try this package https://www.npmjs.com/package/react-native-month-year-picker

I tried this but not working show this error

Failed to resolve dependency 'react-native-month-year-picker@*' (Invalid module ./MonthPicker - Module not found: Error: Can't resolve './MonthPicker' in '/tmp/snackager/snackager/buildStatus/1/react-native-month-year-picker@1.8.1-ios,android,web/package/src')
