### ISSUE TITLE
how to set max time and min time for any date

### ISSUE THREAD

**Issue by anandp926** [react-native-community/react-native-datetimepicker#26]
I have to set minTime and maxTime in date selection irrespective of the date.
So that I can select any date in 10AM - 10PM.

Is this possible in react native datetimepicker

**Comment by dtaborda** [comment]
I just had the same problem, do you know if there is any solution to it?

**Comment by anandp926** [comment]
@dtaborda  I tried to make it this way.[https://gist.github.com/anandp926/c7ab0498b8b80724325a5cf481a06fff](url)

**Comment by anandp926** [comment]
Hey @dtaborda I tried to make it this way. https://gist.github.com/anandp926/c7ab0498b8b80724325a5cf481a06fff

**Comment by MatheusRich** [comment]
@anandp926 Does it work for android?

**Comment by vonovak** [comment]
hello, such option doesn't seem to be supported by the ios api - see [docs](https://developer.apple.com/documentation/uikit/uidatepicker?language=objc) so this will not be implemented in this module.

You can either work around it by checking the submitted date or creating your own component.
