### ISSUE TITLE
Android manual installation instructions are incorrect

### ISSUE THREAD

**Issue by systemride** [react-native-community/react-native-datetimepicker#27]
I'm not sure if the README.md instructions are wrong or if my project is different for some reason, but In building android, I was getting the following failure message:
```
* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':@react-native-community_datetimepicker' could not be found in project ':app'.
```

I was able to fix this and get a successful build by changing `settings.gradle` to:
```
include ':@react-native-community_datetimepicker'
project(':@react-native-community_datetimepicker').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/datetimepicker/android')
```

and `build.gradle` to:
```
implementation project(':@react-native-community_datetimepicker')
```

Is this just me? I can open a PR if you'd like...

**Comment by Josin22** [comment]
same to me

**Comment by cspicuzza** [comment]
@Josin22 @systemride This ended an hour of frustration, thank you.

**Comment by tomasswood** [comment]
I've submitted a PR
https://github.com/react-native-community/react-native-datetimepicker/pull/46

**Comment by eubnara** [comment]
Thanks a lot!

**Comment by Monfernape** [comment]
Seems they haven't updated the Readme section. You saved life here.

**Comment by avbeladiya** [comment]
hello 
i tried @Josin22 and @systemride s solutions , but still getting "app:compileDebugJavaWithJavac FAILED" error while building the project.

**Comment by vonovak** [comment]
The PR with the fix was merged, closing.
