### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): TypeError: Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by whip8466** [react-native-community/react-native-datetimepicker#29]
```
Possible Unhandled Promise Rejection (id: 0):
    TypeError: Cannot read property 'open' of undefined
    TypeError: Cannot read property 'open' of undefined
```

Copy pasted the example code, but it's not working and getting warning message like this.

**Comment by tomjohnhall** [comment]
Also getting this warning using this package after migrating from `DatePickerIOS`

**Comment by tomjohnhall** [comment]
@whip8466 Just got this running, I was on Android and didn't have the following in my `MainApplication.java` file. 

``` 
import com.reactcommunity.rndatetimepicker.RNDateTimePickerPackage;

...

 @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          ...
         new RNDateTimePickerPackage()
      );
    }

...

So it may be something to do with your linking - on older React Native versions you may have to perform some linking steps manually. Check the output of `react-native link @react-native-community/datetimepicker` 

```

**Comment by kjr247** [comment]
I get

```
info Android module [***] is already linked
```

**Comment by pratik72** [comment]
Stop `react-native start` and rebuild your project and run `react-native run-android`.
Again start `react-native start` and check your component. It looks strange but works for me.

**Comment by ElizabethSvit** [comment]
> Stop `react-native start` and rebuild your project and run `react-native run-android`.
> Again start `react-native start` and check your component. It looks strange but works for me.

Didn't work in my case, getting the same warning.

**Comment by vonovak** [comment]
This means the native module is not correctly linked, please follow the installation instructions carefully. Thank you.
