### ISSUE TITLE
Options are not visible on iOS 13 Dark appearance

### ISSUE THREAD

**Issue by ajanauskas** [react-native-community/react-native-datetimepicker#32]
# Bug

When app is in dark appearance selection options are not visible.

Dark appearance turned ON:
<img width="380" alt="Screenshot 2019-09-26 at 16 52 32" src="https://user-images.githubusercontent.com/1474237/65694336-5d759980-e07e-11e9-8a31-a6abeb2fb45f.png">

Dark appearance turned OFF:
<img width="379" alt="Screenshot 2019-09-26 at 16 52 42" src="https://user-images.githubusercontent.com/1474237/65694339-5e0e3000-e07e-11e9-866d-f34f92208581.png">

## Environment info

Library version: 7.5.0

## Steps To Reproduce

1. Install app with react-native-datetimepicker with newest xcode (11)
2. Turn on Dark Mode

Describe what you expected to happen:

1. Date selection options should be visible
2. Date selection options are not visible

**Comment by ajanauskas** [comment]
Woops ! I'm seem to be using different library. Sorry

**Comment by amerdiglisic** [comment]
I think this should be reopened,  I am facing this issue, and if I switch my phone to light mode, it works, but in dark one I do not see the picker values ( probably because text is white ).

**Comment by hiren0412** [comment]
I am also facing this issue. when dark mode is ON, date is not visible in IOS 13.

**Comment by okwast** [comment]
Agreed, we're also facing this issue.

But I guess this issue also tackles the problem: https://github.com/react-native-community/react-native-datetimepicker/issues/44

**Comment by edritech93** [comment]
same for me

**Comment by toxicsebastian** [comment]
Same here, can't find any way to change the dial's text color either.

**Comment by rnnyrk** [comment]
Same here, can't read the text of the DatePicker in dark mode. Forcing the app to by light mode feels a little weird. Any suggestions?
