### ISSUE TITLE
Support Android multiple date selection

### ISSUE THREAD

**Issue by anthonycmain** [react-native-community/react-native-datetimepicker#34]
# Feature Request

The standard Android calendar view allows for multiple dates to be selected and returned. It would be great to expose this property

## Why it is needed

To allow multiple dates to be selected in a single processs

## Possible implementation

Details of the Android properties can be found in this [StackOverflow post](https://stackoverflow.com/questions/25116897/i-want-to-select-multiple-dates-in-calendar-in-android)

I'm not sure what the best way get at the array of dates, rather than a single. The default exposes an additional `getSelectedDates()` method

**Comment by vonovak** [comment]
@anthonycmain thanks for reporting. The SO post you're referring to is about a 3rd party date picker library https://github.com/square/android-times-square from what I can tell. From [this SO](https://stackoverflow.com/questions/45157476/select-multiple-dates-in-android-datepickerdialog/45560625) I understand android itself does not expose this, so I'll close the issue. You can work around the problem by using a 3rd part solution. Thanks.
