### ISSUE TITLE
PLEASE WHEN CAN WE BE ABLE TO USE COLORS AS PROPS 

### ISSUE THREAD

**Issue by jerryheir** [react-native-community/react-native-datetimepicker#36]
# Feature Request
There is a need to use colors based on the theme color of the app we are building. I have worked on three apps and the idea of using this package has been rejected three times because of no flexible when it comes to styling

**Comment by guilleSequeiraWolox** [comment]
Hi, sorry my english is bad but i want to share how i can change theme color of the picker.
in `android/app/src/main/res/values/styles.xml` i put:

```
  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:datePickerDialogTheme">@style/DialogDatePicker.Theme</item>
    </style>

<style name="DialogDatePicker.Theme" parent="Theme.AppCompat.Light.Dialog">
        <item name="colorAccent">@color/ocean_green</item>
        <item name="android:textColor">@color/dove_gray</item>
        <item name="android:textColorPrimary">@color/dove_gray</item>
    </style>
``` 
- colorAccent is the color of header of picker and selector
- textColor is the color of numbers and text buttons
- extColorPrimary is the color of text of month.


I hope it works for you, regards

**Comment by bitfabrikken** [comment]
I have an app that's using the datepicker on iOS on top of a white background.

On iOS 13.2, the color of the datepicker text is now white(!), thus the datepicker is invisible..

Please allow us to set the text colours of the date- and timepicker on iOS.

**Comment by samzer** [comment]
+1 on this issue. This feature is required.

**Comment by jerryheir** [comment]
+1 very much required

**Comment by kitkline** [comment]
+1 great module but useless to us if we cannot style the date picker - seems like a very obvious need?

**Comment by seanquinn** [comment]
+1

**Comment by djlabbe** [comment]
Yes please

**Comment by samzer** [comment]
For now, you can manually change it by editing ```android/app/src/main/res/values/styles.xml.```

More details here -  https://github.com/react-native-community/react-native-datetimepicker/issues/20#issuecomment-545527682

**Comment by vonovak** [comment]
Closing in favor of #20. If you need this, please implement it and contribute a PR, I'll review it.
