### ISSUE TITLE
"Install using react-native link" section missing in README.md

### ISSUE THREAD

**Issue by danlugo92** [react-native-community/react-native-datetimepicker#37]
![image](https://user-images.githubusercontent.com/32064271/66235438-0e52e880-e6be-11e9-856a-eec94b238a5a.png)

It is present in the table of contents though.

**Comment by waleedarshad** [comment]
+1
@danlugo92 are you able to find how to use it using react-native-link?

**Comment by shannonjensen** [comment]
I think it should be `react-native link @react-native-community/datetimepicker`, then `cd ios && pod install`, then `cd ..`

**Comment by ditoglez** [comment]
@waleedarshad:

 `react-native link @react-native-community/datetimepicker && cd ios && pod install`

**Comment by gabrielrra** [comment]
If you're using it with RN 0.60 or up you won't need it, I think that's why they removed

**Comment by joelrorseth** [comment]
@gabrielrra I'm running RN 0.60.3, and running only npm install did not work for me. I was getting the same error reported in [this issue](https://github.com/react-native-community/react-native-datetimepicker/issues/12).

Running @ditoglez command worked perfectly. I have no idea why the link command was removed from the readme (which happened in [this commit](https://github.com/react-native-community/react-native-datetimepicker/commit/74664af2886ef995778f197b19d10087b06d3378#diff-04c6e90faac2675aa89e2176d2eec7d8)), but it looks like it should be put back.

**Comment by vonovak** [comment]
the link command is now present in readme, so closing
