### ISSUE TITLE
Can't use even on fresh start and only using value props

### ISSUE THREAD

**Issue by Stanley521** [react-native-community/react-native-datetimepicker#38]
# Bug

![image](https://user-images.githubusercontent.com/36833134/66308618-c20fde80-e931-11e9-9a20-d2b1fae8ce34.png)

Unable to use the component at all 

## Environment info

npm install -g expo-cli
npm install @react-native-community/datetimepicker --save

React native info output:

[Unhandled promise rejection: TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePickerAndroid.open')]
- node_modules\@react-native-community\datetimepicker\src\datepicker.android.js:42:45 in open$
- node_modules\regenerator-runtime\runtime.js:45:44 in tryCatch
- node_modules\regenerator-runtime\runtime.js:271:30 in invoke
- node_modules\regenerator-runtime\runtime.js:45:44 in tryCatch
- node_modules\regenerator-runtime\runtime.js:135:28 in invoke
- node_modules\regenerator-runtime\runtime.js:170:17 in <unknown>
- node_modules\promise\setimmediate\core.js:45:7 in tryCallTwo
- node_modules\promise\setimmediate\core.js:200:23 in doResolve
- node_modules\promise\setimmediate\core.js:66:12 in Promise
- node_modules\regenerator-runtime\runtime.js:169:27 in callInvokeWithMethodAndArg
- node_modules\regenerator-runtime\runtime.js:192:38 in enqueue
- node_modules\regenerator-runtime\runtime.js:216:8 in async
* null:null in open
- node_modules\@react-native-community\datetimepicker\src\datetimepicker.android.js:42:39 in RNDateTimePicker
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:9473:27 in renderWithHooks
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:11994:6 in mountIndeterminateComponent
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17276:21 in performUnitOfWork
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17316:41 in workLoop
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17417:15 in renderRoot
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18423:17 in performWorkOnRoot
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18324:24 in performWork
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18285:14 in performSyncWork
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18169:19 in requestWork
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17969:16 in scheduleWork
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:10221:17 in dispatchAction
* App.js:54:21 in handleFinishLoading
* App.js:18:44 in onFinish
- node_modules\expo\build\launch\AppLoading.js:31:20 in _callee$
- node_modules\regenerator-runtime\runtime.js:45:44 in tryCatch
- ... 14 more stack frames from framework internals

Library version: x.x.x

## Steps To Reproduce

1. npm install @react-native-community/datetimepicker --save
2. import DateTimePicker from '@react-native-community/datetimepicker';
3. <DateTimePicker value={new Date()}/>
...

Describe what you expected to happen:

1. To use the component
2. No warning shown

## Reproducible sample code

https://github.com/Stanley521/AwesomeProject

**Comment by jekcom** [comment]
same here

**Comment by marcaaron** [comment]
Happens for me on Android fwiw.

**Comment by 5ervant** [comment]
For a moment `@react-native-community/datetimepicker` is not yet working with Expo right now.

As an alternative, you can use [`TimePickerAndroid`](https://docs.expo.io/versions/latest/react-native/timepickerandroid/), [`DatePickerIOS`](https://docs.expo.io/versions/latest/react-native/datepickerios/) or https://github.com/xgfe/react-native-datepicker for multi-platform. Unfortunately, neither of them works with Expo Web.

I hope they will soon work.

**Comment by stevreeper** [comment]
Having the same problem here, anyone found a solution?

**Comment by NullPointerExceptionBear** [comment]
> For a moment `@react-native-community/datetimepicker` is not yet working with Expo right now.
> 
> As an alternative, you can use [`TimePickerAndroid`](https://docs.expo.io/versions/latest/react-native/timepickerandroid/), [`DatePickerIOS`](https://docs.expo.io/versions/latest/react-native/datepickerios/) or https://github.com/xgfe/react-native-datepicker for multi-platform. Unfortunately, neither of them works with Expo Web.
> 
> I hope they will soon work.

Do we have an idea when they will work? According to react native [docs](https://facebook.github.io/react-native/docs/timepickerandroid) , TimePickerAndroid will be deprecated and moved to DateTimePicker in a future release.

**Comment by 5ervant** [comment]
@NullPointerExceptionBear DateTimePicker is already working for iOS and Android.
If you're in Expo you can use: https://github.com/xgfe/react-native-datepicker

Unfortunately, neither of them works in Expo Web, I don't know about `react-native-web`.

**Comment by bkotos** [comment]
I'm also getting the same issue on android when trying to use this package with expo.  It kind of sucks that they're evangelizing something in the documentation that's basically broken.

@stevreeper @NullPointerExceptionBear this component from NativeBase seems to work out of the box for me:
https://docs.nativebase.io/Components.html#date-picker-def-headref

It doesn't support selecting time, but for selecting dates it works for me.

**Comment by zain148** [comment]
i'm also having the same issue is anyone there to help and finalize this issue?

**Comment by marcosdourado** [comment]
I had the same problem, and I don't know exactly what the solution was.

In a clean installation, the component worked as expected. And it made me think that there was a problem with my configuration files, so here's what I did:

in `android/settings.gradle` it looked like this:

```
rootProject.name = 'Todo'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':WebRTCModule', ':app'
project(':WebRTCModule').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webrtc/android')
```

and then I left it like this:

```
rootProject.name = 'Todo'
include ':WebRTCModule', ':app'
project(':WebRTCModule').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webrtc/android')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
```

I cleared the build cache:

`cd android && ./gradlew cleanBuildCache && cd ..`

I removed node_moludes:

`rm -rf node_modules  
`

and then I ran android again and everything worked.

> Note that the commands will not work on windows

**Comment by vonovak** [comment]
@Stanley521 your runnable repro depends on expo 35, but date picker was added to expo in version 36 from what I read in some other issue.

In case such error is thrown in a vanilla RN project, it's because the module was not correctly linked. Thank you.
