### ISSUE TITLE
RNDatePickerDialogFragment.java uses or overrides a deprecated API. error when build as release with react-native -v 0.60.5

### ISSUE THREAD

**Issue by ponleukea** [react-native-community/react-native-datetimepicker#40]
/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

**Comment by Deg5112** [comment]
Hey @Swaagie,

this appears to be an issue can we get confirmation on when this will be resolved? We will have to find an alternative date picker package for the time being. Thank you

**Comment by ventr1x** [comment]
This issue exists for months without resolution. Don't bet any money on a fix.

**Comment by Deg5112** [comment]
Okay we’ll just have to fork the repo and fix it ourselves then. If the authors are going to be unresponsive they should just say so on the read me that the repo is no longer maintained as opposed to just ignoring everyone

**Comment by ventr1x** [comment]
The problem mostly comes from this plugin not using androidx.
Installing jetifier, cleaning node_modues/caches and manually running npx jetify helped. The react cli should to that automatically, but it is quite buggy and unstable.

**Comment by Deg5112** [comment]
@ventr1x i added a postinstall script for npx jetify so it'll run automatically post npm install

**Comment by vonovak** [comment]
we're using androidX now so this should not be a problem any more. please open a new issue if problem persists
