### ISSUE TITLE
Data type  wrongly given by react-native-datetimepicker

### ISSUE THREAD

**Issue by isaacp0310** [react-native-community/react-native-datetimepicker#43]
**Hi, i am trying to get the response that react-native-datetimepicker gives me once i choose the time.
it just send me a plain text data, instead of an array.**

Here is my code:

```
     <DateTimePicker
      value={new Date()}
      mode='time'
      is24Hour={true}
      display="default"
      onChange={(event,newDate) => this.setDate(newDate)}
      />

```
//This is the function

```
  setDate = (date) => {
   console.log(date);
};
```
**IF i choose the 12 hour format how do i know if the user has chosen AM or PM?** 

![Screenshot_1](https://user-images.githubusercontent.com/35440957/66712077-5086c480-ed65-11e9-924b-b8b5f2c56072.png)

the modal appears correctly but when i had choosen the time

it gives me just this plain text

![Screenshot_3](https://user-images.githubusercontent.com/35440957/66712111-bc692d00-ed65-11e9-9cf7-a65a7e1b7ba4.png)

but the data that i really wanna save are specifically these:

-HOUR
-MINUTE

**Comment by giautm** [comment]
Hi, `date` was actually `Date` object, you can looking for the reference from [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)

console.log was print formatted version of date, like this:
<img width="378" alt="Screen Shot 2019-10-14 at 5 09 46 PM" src="https://user-images.githubusercontent.com/12751435/66744114-cabe6280-eea5-11e9-9375-35b87cc66d4f.png">

**Comment by isaacp0310** [comment]
Ok, i understand but 
how can i fetch the
User selected hour and minute and period(AM/PM)?

**Comment by giautm** [comment]
If you want to format date time to Hour:minutes AM/PM format, you can use [`format`](https://date-fns.org/v2.0.1/docs/format) function from [date-fns](https://date-fns.org/v2.0.1/docs/) library like this:
`dateFns.format(new Date(), 'hh:mm A')`
<img width="353" alt="Screen Shot 2019-10-17 at 4 24 43 PM" src="https://user-images.githubusercontent.com/12751435/66996375-d3f43d00-f0fa-11e9-98d7-734006c4ab75.png">

Or if you want get raw values, just compare hours with 12, great than 12 is PM.
<img width="182" alt="Screen Shot 2019-10-17 at 4 27 13 PM" src="https://user-images.githubusercontent.com/12751435/66996532-1c135f80-f0fb-11e9-9305-dd7da88f731c.png">

**Comment by isaacp0310** [comment]
Wow a lot of thanks!
