### ISSUE TITLE
how to make the Component not show anything on the screen?

### ISSUE THREAD

**Issue by BravenxX** [react-native-community/react-native-datetimepicker#45]
# Question

how to make the Component not show anything on the screen? I tried this. but DateTimePicker still show me on the screen: "Thu, 17Oct ...." I just want to show {date} on the screen.

    <View>
      <Text onPress={setShouldDatePickerShow}>{date}</Text>

      {shouldDatePickerShow && (
          <DateTimePicker
            value={fechaEjecucionActReal}
            mode={"date"}
            is24Hour={true}
            display="default"
            onChange={(e, newDate) => {
              setShouldDatePickerShow(false);
              newDate && onChangeFechaEjecucion(newDate);
            }}
            maximumDate={new Date(Date.now())}
          />
      )}
    </View>

**Comment by BravenxX** [comment]
Pls close, its was because another component.

**Comment by robertototti** [comment]
in my case this is work
`
import React, {useState} from 'react';
import {Button} from 'react-native';

const ExampleComponent = props => {
  const [visible, setVisible] = useState(false);
  const [chosenDate, setChosenDate] = useState(new Date());
  const setDate = (event, date) => {
    setVisible(false);
    if (date) {
      setChosenDate(date);
    }
  };
  
  return (
    <View>
      <Button title="Show DatePicker" onPress={() => setVisible(true)} />
      {visible ? <DateTimePicker value={chosenDate} onChange={setDate} /> : null}
    </View>
  )
}

export default ExampleComponent;
`
