### ISSUE TITLE
Warning: DatePickerAndroid has been merged with DatePickerIOS and will be removed

### ISSUE THREAD

**Issue by FDiskas** [react-native-community/react-native-datetimepicker#48]
```
Warning: DatePickerAndroid has been merged with DatePickerIOS and will be removed in a future release. It can now be installed and imported from '@react-native-community/datetimepicker' instead of 'react-native'. See https://github.com/react-native-community/react-native-datetimepicker
```

**Comment by kabitacode** [comment]
same with me, have you found a solution?

**Comment by robertototti** [comment]
just read documentation how to migrate from old component to new way
https://github.com/react-native-community/react-native-datetimepicker#migration-from-the-older-components

**Comment by vonovak** [comment]
This is a warning coming from react native itself. If you migrate over to this module and don't import date picker from react native, it will go away.
