### ISSUE TITLE
Shows blank screen

### ISSUE THREAD

**Issue by bastolaxantos** [react-native-community/react-native-datetimepicker#52]
# Question

![43F66E60-C1D9-4FCA-9EE2-12520244ABC2](https://user-images.githubusercontent.com/24861728/68288087-e3d4c080-00ab-11ea-8612-f308672c00a2.jpg)

sometime it shows blank screen instead of picker.

am I doing something wrong or this is a bug?

**Comment by Jojr** [comment]
@bastolaxantos  We are having this same problem here
How you solve that?

**Comment by Jojr** [comment]
In my case this was caused by "Dark Mode" feature on IOS 13+.
I solve that by adding this key to the info.plist:

`<key>UIUserInterfaceStyle</key>`
`<string>Light</string>`

Found solution here:
https://github.com/facebook/react-native/issues/26299#issuecomment-540261084

**Comment by mi5ha** [comment]
> In my case this was caused by "Dark Mode" feature on IOS 13+.
> I solve that by adding this key to the info.plist:
> 
> `<key>UIUserInterfaceStyle</key>`
> `<string>Light</string>`

But what to do if UI is not light?

**Comment by apoorvkarkare** [comment]
Did anyone find any solution to this? I am getting the same on Android device.
