### ISSUE TITLE
How to use this in Expo?

### ISSUE THREAD

**Issue by yesIamFaded** [react-native-community/react-native-datetimepicker#53]
Hi there I dont know how active ppl are in here and I dont know why the datetimepicker is given to the community but I have a Question.

How do I implement this module inside an Expo app? I have a different datetimepicker that works in expo because it doesnt have to change android files. And obviously you have to change some Android files to use this one.

Do I really need to eject just to use this package? Because that looks kinda stupid to me.

**Comment by clu7ch3r** [comment]
It's incompatible. Use this https://github.com/mmazzarolo/react-native-modal-datetime-picker

**Comment by rshov** [comment]
Maybe the readme should be updated to state that there is no expo support yet. I just installed and setup with an expo app only to find that it doesn't work at all. Looks like a nice component though, I'll have to try with the react-native-modal-datetime-picker instead for now.

**Comment by saniagh** [comment]
I also think this should be stated in the README

**Comment by lundcm** [comment]
I understood this to be now usable in Expo now that SDK36 is out: https://expo.canny.io/feature-requests/p/add-react-native-datetimepicker-module-to-expo

The example in the readme seems to work except the dark mode issues with this package. I'm probably going to stick with `react-native-modal-datetime-picker` until dark mode works here. In SDK36 you get warnings that DateTimePickerIOS/Android is deprecated though. No perfect options.

**Comment by Manubi** [comment]
expo has added it in sdk 36. have loook here in the [expo docu.](https://docs.expo.io/versions/latest/sdk/date-time-picker/)
