### ISSUE TITLE
Format date

### ISSUE THREAD

**Issue by Skynear2** [react-native-community/react-native-datetimepicker#60]
# Question
Hello, I would like to change the format of the date shown. 
As shown: yyyy-mm-dd

I would like to change to:
dd-mm-yyyy

**Comment by j320** [comment]
Did you manage to do this?

**Comment by creative-ae** [comment]
I CANNOT BELIEVE THAT SUCH A DATE PICKER HAS NO FDATE FORMATING OPTION !!!

**Comment by dhirajanand014** [comment]
We need a formatting option. react-date-picker which is older than this has those options.
