### ISSUE TITLE
In compatible with expo (expo links to this repo)

### ISSUE THREAD

**Issue by mayerlench** [react-native-community/react-native-datetimepicker#63]
Expo links to this repo and it is not compatible with expo.

This is either a bug or a mistake.

https://docs.expo.io/versions/v36.0.0/sdk/date-time-picker/

**Comment by Trashpants** [comment]
im using this right now in an expo app - you need to have SDK 36 as of time putting this up its been out for about a day - have you upgraded your SDK version?

**Comment by mayerlench** [comment]
@Trashpants Yup confirmed. I updated my sdk and it works now.
Thanks
