### ISSUE TITLE
Allow for placeholder text and null selection in picker's initial display (i.e. MM DD YYYY)

### ISSUE THREAD

**Issue by rgordon95** [react-native-community/react-native-datetimepicker#64]
# Feature Request

Allow for initial date to be set to a blank date or a string, such as "MM DD YYYY" with the selector wheel on ios set to "-- -- ----". 

EDIT: This would also go hand in hand with allowing a placeholder in the display.

## Why it is needed

Setting a date to an arbitrary or the new current date can become cumbersome for users or alienating. 

## Possible implementation

Allow for types other than date objects to be passed in as the initial date or selected on the scroll wheel.

**Comment by vonovak** [comment]
hello, thanks for reporting. The backing `UIDatePicker` does not allow such functionality, so we cannot implement it. Workaround is to use some 3rd party component for this. Thank you.
