### ISSUE TITLE
android Flat datetimepicker instead of modal

### ISSUE THREAD

**Issue by billel-boudchicha** [react-native-community/react-native-datetimepicker#69]
# Question

As i mentioned in the title , the android datepicker always rendered in modal .
How can i disable the modal , like the IOS version (Flat)
thank you

**Comment by vonovak** [comment]
this should be doable - see https://mkyong.com/android/android-date-picker-example/ or https://www.tutlane.com/tutorial/android/android-timepicker-with-examples

contributions are welcome

**Comment by vonovak** [comment]
closing in favor of https://github.com/react-native-community/react-native-datetimepicker/issues/14
