### ISSUE TITLE
Time mode. Wrong time

### ISSUE THREAD

**Issue by tungcao** [react-native-community/react-native-datetimepicker#79]
# Wrong time
I use:
- RN version 0.61.4
- Expo version 3.11.3

I choose 8:30PM but show 2020-06-20T13:30:42.000Z
Image attach
<img width="546" alt="Screen Shot 2020-01-02 at 14 58 58" src="https://user-images.githubusercontent.com/12287499/71657034-92297900-2d70-11ea-95ab-30a27bda2c03.png">

My Code:
> <DateTimePicker value={date}
>                         mode={time}
>                         display="default"
>                         minuteInterval={15}
>                         // locale="vi-VN"
>                         onChange={(event, date) => {
>                             date = date || this.state.date;
>                             console.log(date)
>                             this.setState({
>                                 show: Platform.OS === 'ios' ? true : false,
>                                 date,
>                             });
>                         }}
>                     />

Please help me!!!

**Comment by tungcao** [comment]
I solved my issue.
I don't know new Date() format. But when I format date with moment, correct time!
`console.log(moment(date).format('YYYY-MM-DD HH:mm:ss'))`

<img width="672" alt="Screen Shot 2020-01-02 at 16 45 52" src="https://user-images.githubusercontent.com/12287499/71661005-61047500-2d7f-11ea-971e-5a15f837f4bc.png">

My code:
> <DateTimePicker value={date}
> mode={time}
> display="default"
> minuteInterval={15}
> // locale="vi-VN"
> onChange={(event, date) => {
> date = date || this.state.date;
> console.log(moment(date).format('YYYY-MM-DD HH:mm:ss'))
> this.setState({
> show: Platform.OS === 'ios' ? true : false,
> date,
> });
> }}
> />

**Comment by plaporte** [comment]
I'm having this same issue and formatting with moment is giving me a time that's 5 hours behind what is selected on the date picker. Any ideas?

**Comment by geeky1Coder** [comment]
sa

**Comment by geeky1Coder** [comment]
@plaporte you can use moment to format the date and time according to way you want

**Comment by khayym** [comment]
You can use simply toLocaleString function:
 `onConfirm={(timestamp: any): void => {
          console.log('time: ', timestamp.toLocaleString())
    }}`
