### ISSUE TITLE
on Cancel

### ISSUE THREAD

**Issue by lalitchoudhary10007** [react-native-community/react-native-datetimepicker#83]
# Bug

{show && <DateTimePicker value={new Date()}
                            mode={'date'}
                            minimumDate={new Date("2020-01-06")}
                            is24Hour={true}
                            display="default"
                            onChange={this.setDate}
                             />
                        }

 setDate = (event, date) => {
           this.setState({
                pickdate: moment.utc(date).format('MM/DD/YYYY'),
                show: Platform.OS === 'ios' ? true : false,
              })
        }

library version :- "@react-native-community/datetimepicker": "^2.1.0",

on click cancel also this.setDate method is calling because of this on cancel click also date is selecting...
is there any different callbacks for ok and cancel ?

**Comment by simofilahi** [comment]
i had the same problem the props onCancel not found but i fix my problem by small trick check if date passed trough setDate if undefined so the cancel button was clicked

**Comment by AbdelkhalekESI** [comment]
@simofilahi thanks , it's work !

**Comment by lalitchoudhary10007** [comment]
@simofilahi thanks a lot..

**Comment by ayoubkamli** [comment]
@simofilahi thanks

**Comment by yazmnh87** [comment]
Anyone aware of how to run a function when clicking 'OK'?

**Comment by makuraso123** [comment]
> Anyone aware of how to run a function when clicking 'OK'?


183/5000
Hi

the event for datetimepicker has two types of status when you click

dismissed = calcel
set = is modified

validate what type of event is activated and will work without problems

**Comment by kim-nguyenkhn** [comment]
This pattern should be added to the documentation.

**Comment by AdarshJais** [comment]
@simofilahi  Can you please tell me how to do so.I am new on this

**Comment by simofilahi** [comment]
@AdarshJais setDate take an argument, all you is to check this argument is it undefined so you clicked cancel.
If you still don't understand how to do that, paste ur code here and will see where is the problem

**Comment by Chasty** [comment]
You can use the event.
```
if(event.type == "set") {
        //ok button clicked
    } else {
         //cancel button clicked
    }
```

**Comment by omar-bakhsh** [comment]
you can listen to event onChange 
```
 const onChange = (event, selectedDate) => {

        const currentDate = selectedDate || date;
        // add selected date . 
    // set  date show to null = hide 
        set_date_state({ show: null })
        
        }
```

**Comment by nknaveen007** [comment]
this is my project .

const onChange = (event, selectedDate) => {
      const currentDate = selectedDate || date;
      setShow(Platform.OS === 'ios');
      if(event.type == "set") {      //ok button
        setDate(currentDate)
   
    } else {                                 //cancel Button
        return null
    }

**Comment by DOZBORNE** [comment]
Whenever I click okay on Android, I keep getting the date selector popping back up. I'm not sure how to get rid of it. Using event.type == "set" just resets the value. And then triggers the onChange function over again. I'm not sure why.

**Comment by DOZBORNE** [comment]
`
  useEffect(() => {
    formatDate();
  }, [date]);

  function changeDate(event, selectedDate) {
    console.log(event);
    const currentDate = selectedDate || date;
    if (event.type == "set") {
      setDate(currentDate);
      return;
    } else if (event.type == "dismissed") {
      // dismissedAction
      return;
    } else {
      setDate(currentDate);
    }

    // console.log(event);
    // if (event.type == "set") {
    //   setDate(selectedDate);
    //   return;
    // }
    // // setShow(Platform.OS === 'ios');
    // setDate(currentDate);
    // if (date !== undefined) {
    //   setDate(selectedDate);
    // } else {
    //   return; // setDate(selectedDate);
    // }
  }

  function formatDate() {
    var d = date,
      month = "" + (d.getMonth() + 1),
      day = "" + d.getDate(),
      year = d.getFullYear();

    if (month.length < 2) month = "0" + month;
    if (day.length < 2) day = "0" + day;

    const formattedDate = [month, day, year].join("/");
    setTextDate(formattedDate);
  }

  return (
    <ScrollView>
      <View style={styles.form}>
        <View style={styles.formControl}>
          <Text style={styles.label}>Merchant</Text>
          <TextInput
            style={styles.input}
            value={formState.inputValues.merchant}
            onChangeText={textChangeHandler.bind(this, "merchant")}
            keyboardType="default"
            autoCapitalize="words"
            required
            autoCorrect
            clearButtonMode="while-editing"
            minLength={2}
            returnKeyType="next"
            onBlur={lostFocusHandler.bind(this, "merchant")}
          />
          {!formState.inputValidities.merchant && isTouched.merchant && (
            <View style={styles.errorContainer}>
              <Text style={styles.errorText}>
                Please enter a valid merchant!
              </Text>
            </View>
          )}
          <Text style={styles.label}>Total</Text>
          <TextInput
            style={styles.input}
            value={formState.inputValues.total}
            clearButtonMode="while-editing"
            returnKeyType="next"
            minLength={1}
            maxLength={10}
            required
            keyboardType="number-pad"
            onChangeText={textChangeHandler.bind(this, "total")}
            onBlur={lostFocusHandler.bind(this, "total")}
          />
          {!formState.inputValidities.total && isTouched.total && (
            <View style={styles.errorContainer}>
              <Text style={styles.errorText}>Please enter a valid amount!</Text>
            </View>
          )}
          <Text style={styles.label}>Date</Text>
          <View style={styles.input}>
            <Text style={styles.dateInput} onPress={showMode}>
              {textDate}
            </Text>
          </View>
          {show && (
            <DateTimePicker
              testID="dateTimePicker"
              value={new Date()}
              mode="date"
              display={Platform.OS === "ios" ? "spinner" : "spinner"}
              onChange={changeDate}
              maximumDate={new Date()}
              minimumDate={new Date(2014, 6, 1)}
            />
          )}
        </View>
        <View style={styles.buttonContainer}>
          <Button
            title="Add Expense"
            onPress={submitHandler}
            color={Platform.OS === "ios" ? "white" : Colors.green}
          />
        </View>
      </View>
    </ScrollView>
  );
};`

**Comment by DOZBORNE** [comment]
`
  useEffect(() => {
    formatDate();
  }, [date]);

  function changeDate(event, selectedDate) {
    console.log(event);
    const currentDate = selectedDate || date;
    if (event.type == "set") {
      setDate(currentDate);
      return;
    } else if (event.type == "dismissed") {
      // dismissedAction
      return;
    } else {
      setDate(currentDate);
    }

    // console.log(event);
    // if (event.type == "set") {
    //   setDate(selectedDate);
    //   return;
    // }
    // // setShow(Platform.OS === 'ios');
    // setDate(currentDate);
    // if (date !== undefined) {
    //   setDate(selectedDate);
    // } else {
    //   return; // setDate(selectedDate);
    // }
  }

  function formatDate() {
    var d = date,
      month = "" + (d.getMonth() + 1),
      day = "" + d.getDate(),
      year = d.getFullYear();

    if (month.length < 2) month = "0" + month;
    if (day.length < 2) day = "0" + day;

    const formattedDate = [month, day, year].join("/");
    setTextDate(formattedDate);
  }

  return (
    <ScrollView>
      <View style={styles.form}>
        <View style={styles.formControl}>
          <Text style={styles.label}>Merchant</Text>
          <TextInput
            style={styles.input}
            value={formState.inputValues.merchant}
            onChangeText={textChangeHandler.bind(this, "merchant")}
            keyboardType="default"
            autoCapitalize="words"
            required
            autoCorrect
            clearButtonMode="while-editing"
            minLength={2}
            returnKeyType="next"
            onBlur={lostFocusHandler.bind(this, "merchant")}
          />
          {!formState.inputValidities.merchant && isTouched.merchant && (
            <View style={styles.errorContainer}>
              <Text style={styles.errorText}>
                Please enter a valid merchant!
              </Text>
            </View>
          )}
          <Text style={styles.label}>Total</Text>
          <TextInput
            style={styles.input}
            value={formState.inputValues.total}
            clearButtonMode="while-editing"
            returnKeyType="next"
            minLength={1}
            maxLength={10}
            required
            keyboardType="number-pad"
            onChangeText={textChangeHandler.bind(this, "total")}
            onBlur={lostFocusHandler.bind(this, "total")}
          />
          {!formState.inputValidities.total && isTouched.total && (
            <View style={styles.errorContainer}>
              <Text style={styles.errorText}>Please enter a valid amount!</Text>
            </View>
          )}
          <Text style={styles.label}>Date</Text>
          <View style={styles.input}>
            <Text style={styles.dateInput} onPress={showMode}>
              {textDate}
            </Text>
          </View>
          {show && (
            <DateTimePicker
              testID="dateTimePicker"
              value={new Date()}
              mode="date"
              display={Platform.OS === "ios" ? "spinner" : "spinner"}
              onChange={changeDate}
              maximumDate={new Date()}
              minimumDate={new Date(2014, 6, 1)}
            />
          )}
        </View>
        <View style={styles.buttonContainer}>
          <Button
            title="Add Expense"
            onPress={submitHandler}
            color={Platform.OS === "ios" ? "white" : Colors.green}
          />
        </View>
      </View>
    </ScrollView>
  );
};`

**Comment by macs054** [comment]
> Whenever I click okay on Android, I keep getting the date selector popping back up. I'm not sure how to get rid of it. Using event.type == "set" just resets the value. And then triggers the onChange function over again. I'm not sure why.

I have the same issue, every time I pick a different date it keeps popping up until I choose the same date twice.

**Comment by hani-q** [comment]
> > Anyone aware of how to run a function when clicking 'OK'?
> 
> 183/5000
> Hi
> 
> the event for datetimepicker has two types of status when you click
> 
> dismissed = calcel
> set = is modified
> 
> validate what type of event is activated and will work without problems

This is awesome... was struggling with my own hackery....

**Comment by ckswopnera** [comment]
I had the same problem. here is my code for android and ios-->

onChangeStart(event, selectedDate) {
    let currentDate = selectedDate || this.state.deadlineDate;
    // console.log("event",event)
    if(Platform.OS=="ios"){
      this.setState({
        visible: Platform.OS === "ios",
        deadlineDate: currentDate,
      });
      let mydate = JSON.stringify(currentDate)
        .split("T")[0]
        .trim()
        .replace('"', "");
    
      // console.log("mydatestart", mydate);
    
      this.setState({ startDate: mydate });
    }
    else{if(event.type == "dismissed") {          //ok button
      this.setState({
        visible: Platform.OS === "ios",
        startDate: null
      });
      
} else if(Platform.OS=="android") {                                    //cancel Button
  this.setState({
    visible: Platform.OS === "ios",
    deadlineDate: currentDate,
  });
  let mydate = JSON.stringify(currentDate)
    .split("T")[0]
    .trim()
    .replace('"', "");

  // console.log("mydatestart", mydate);

  this.setState({ startDate: mydate });
}}
  
  }

**Comment by mr-abdellah** [comment]
> if(event.type == "set") {          //ok button
> 
>                   setDate(currentDate)
>         } else {                                    //cancel Button
>                  return null
>       }

-----
dude thanks sm , this work well <3

**Comment by charbelmansour005** [comment]
> const onChange = (event, selectedDate) => {         //add the if else function inside the onChange function
> 
>    const currentDate = selectedDate || date;
>   
>  setShow(Platform.OS=== 'ios');
>         
>           if(event.type == "set") {          //ok button
> 
>                   setDate(currentDate)
>         } else {                                    //cancel Button
>                  return null
>       }

Still works - 15 Feb 2023
