### ISSUE TITLE
Date picker value.getTime() error

### ISSUE THREAD

**Issue by ctohster** [react-native-community/react-native-datetimepicker#86]
Not really a bug just leaving it here in case it can help someone

I realised for iOS that if you have mode='date' (or default value) you also need to set is24Hour={true} otherwise you get an error

**Comment by MamboMaya** [comment]
@ctohster did how did you solve this?

**Comment by ctohster** [comment]
onChange={(e, d) => setDate(d)}

**Comment by Steffi3rd** [comment]
Yes, thanks for this fix. 

I had this error too. This error happens is the DateTimePicker `value` is not a type of Date() anymore. 

Example : 

```

const [date, setDate] = useState(new Date());

useEffect( () => {

    // Do something to alter the date and not renders a date anymore.
   setDate( moment(date).format('YYYY-MM-DD') );

}, []);

return (
   <DateTimePicker
       maximumDate={new Date()}
       value={date}
       mode="date"
       onChange={(e, selectedDate) => {
           setDate(selectedDate);
       }}
   />
)

```

**Comment by michaldobiezynski** [comment]
This worked for me:

`    <DateTimePicker
                testID="dateTimePicker"
                value={workout.date}
                mode={"date"}
                display="default"
                onChange={(event, date) => {
                  setWorkout({ ...workout, date: new Date(date) });
                }}
              />`
