### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by sorinsinz** [react-native-community/react-native-datetimepicker#87]
# Question

I would like to know if this repo is still maintained because I tried using this library and found quite a few bugs and if it is not anymore I can just fork and fix the things I need. Last commit to master was in 2019 at the beginning of September and there are a few issues and pull requests without anyone answering or anything, that's why I am asking. 

Thank you very much.

**Comment by rafaelcavalcante** [comment]
You may fork and open a pull request to fix the bugs, right?

**Comment by sorinsinz** [comment]
@rafaelcavalcante if there isn't anybody to merge PRs then I guess the only thing left is to fork.

That repo uses this library, I would rather fix the things I need instead of adding another layer of abstraction. Thanks for the help anyway! :)

**Comment by mmazzarolo** [comment]
> You may fork and open a pull request to fix the bugs, right?
> 
> Maybe you want to take a look: https://github.com/mmazzarolo/react-native-modal-datetime-picker

`react-native-modal-datetime-picker` maintainer here 👋 
We're using `react-native-datetimepicker` under the hood (because it's the officially supported lib now) so we can't do fixes on the native layer on our end :/

Let me know if I can help here.

**Comment by vonovak** [comment]
Hello! I'm planning to use the module in production and so I'll help with necessary maintenance, bug fixes and potentially releases in the near future.

I've already merged a few PRs and will continue making the lib more stable.

Given that I contribute / maintain a few other repositories I'll try to include more people in maintenance, especially major PR authors.

If something is missing, please don't hesitate to open a PR with a detailed motivation for given change. Thank you.

**Comment by netgfx** [comment]
Some documentation on how to position the datetimepicker would be nice, seeing that the feature/bug request to render it by default on the bottom like iOS does, was abruptly closed and locked for discussion.
