### ISSUE TITLE
IS selecting a Date Range possible?

### ISSUE THREAD

**Issue by abhi06991** [react-native-community/react-native-datetimepicker#89]
Mine is a hotel booking application. So, if a user wants to book a hotel for particular two dates, is selecting two dates possible?

**Comment by vonovak** [comment]
hello, this module does not support this, and there are currently no plans to support it. Doing range selection with picker on ios doesn't even make much sense imho so not sure if this is feasible. Thank you.

**Comment by aprilmintacpineda** [comment]
Hmmm, so is date range not a good feature for a date picker?
