### ISSUE TITLE
Highlight or Mark specific dates

### ISSUE THREAD

**Issue by Miteshdv** [react-native-community/react-native-datetimepicker#95]
# Feature Request
Need to Highlight Specific dates

## Why it is needed
Need to Highlight Birthdays or Specific event dates

## Possible implementation
Custom day renderer

**Comment by vonovak** [comment]
Hello, thank you for the feature request. I'm not aware of such functionality being present in the native date pickers, and therefore I'm closing the issue - no such functionality can be implemented using the native apis as far as I know. Please open a new issue or PR if you find out such functionality is available. Thank you.
