### ISSUE TITLE
DateTimePicker Android onConfirm prop

### ISSUE THREAD

**Issue by yazmnh87** [react-native-community/react-native-datetimepicker#96]
is anyone aware of an onConfirm prop for android?  This was available from the RN library component, how do you trigger an action with the 'OK' button?

There is logic for the 'CANCEL' button although waiting for the onChange to update state is not working for me. TIA.

**Comment by somushanker44** [comment]
There is no logic for 'CANCEL' manually.

**Comment by yazmnh87** [comment]
> There is no logic for 'CANCEL' manually.

For the cancel button, the logic below works. Although I wanted to setState when the 'OK' button was pressed.  I got something working but the previous androiddatepicker had an onConfirm prop

etTime = (event, date) => {
  if (date === undefined) {
    // dismissedAction
  }
}

**Comment by gagan-aryan** [comment]
How did you setState when the 'OK' button was pressed? I am stuck with this.

**Comment by jackdewhurst** [comment]
Me too, @yazmnh87 did you figure this out?
